DROP TABLE PLANTA CASCADE CONSTRAINTS;

DROP TABLE OPERACAO CASCADE CONSTRAINTS;

DROP TABLE PARCELA_AGRICOLA CASCADE CONSTRAINTS;

DROP TABLE CULTURA CASCADE CONSTRAINTS;

DROP TABLE FATOR_PRODUCAO CASCADE CONSTRAINTS;

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

DROP TABLE COMPONENTE CASCADE CONSTRAINTS;

DROP TABLE TIPO_PLANTA CASCADE CONSTRAINTS;

DROP TABLE SEMEADURA CASCADE CONSTRAINTS;

DROP TABLE MONDA CASCADE CONSTRAINTS;

DROP TABLE PLANTACAO CASCADE CONSTRAINTS;

DROP TABLE REGA CASCADE CONSTRAINTS;

DROP TABLE COLHEITA CASCADE CONSTRAINTS;

DROP TABLE MOVIMENTACAO_SOLO CASCADE CONSTRAINTS;

DROP TABLE APLICACAO_FP_SOLO CASCADE CONSTRAINTS;

DROP TABLE APLICACAO_FP CASCADE CONSTRAINTS;

DROP TABLE APLICACAO_FP_CULTURA CASCADE CONSTRAINTS;

DROP TABLE MODO_AFP CASCADE CONSTRAINTS;

DROP TABLE FP_APLICADOS CASCADE CONSTRAINTS;

DROP TABLE SETOR CASCADE CONSTRAINTS;

DROP TABLE FERTIRREGA CASCADE CONSTRAINTS;

DROP TABLE RECEITA_FERTIRREGA CASCADE CONSTRAINTS;

DROP TABLE FP_RECEITA CASCADE CONSTRAINTS;

DROP TABLE PODA CASCADE CONSTRAINTS;

CREATE TABLE PLANTA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  NOME VARCHAR2(200) NOT NULL,
  TIPO_PLANTA_ID NUMBER(10) NOT NULL,
  TIPO_PLANTACAO VARCHAR2(255) NOT NULL CHECK(TIPO_PLANTACAO IN ('Temporaria', 'Permanente')),
  PRIMARY KEY (ID),
  CONSTRAINT UNIQUE_PLANTA UNIQUE (TIPO_PLANTA_ID, NOME)
);

CREATE TABLE OPERACAO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DATA TIMESTAMP(0) NOT NULL,
  ESTADO VARCHAR2(255) DEFAULT 'sucedida' NOT NULL CHECK(ESTADO IN ('sucedida', 'anulada', 'pendente')),
  PRIMARY KEY (ID)
);

CREATE TABLE PARCELA_AGRICOLA (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(50) NOT NULL UNIQUE,
  AREA FLOAT(5) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CULTURA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DATA_INICIAL TIMESTAMP(0) NOT NULL,
  DATA_FINAL TIMESTAMP(0),
  PARCELA_ID NUMBER(10) NOT NULL,
  PLANTA_ID NUMBER(10) NOT NULL,
  SETOR_ID NUMBER(10),
  PRIMARY KEY (ID),
  CONSTRAINT UNQIUEIDENTIFIER UNIQUE (DATA_INICIAL, PARCELA_ID, PLANTA_ID)
);

CREATE TABLE FATOR_PRODUCAO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(50) NOT NULL UNIQUE,
  FABRICANTE VARCHAR2(50) NOT NULL,
  FORMATO VARCHAR2(50) NOT NULL,
  TIPO VARCHAR2(50) NOT NULL,
  APLICACAO VARCHAR2(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(200) NOT NULL,
  PLANTA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE COMPONENTE (
  FATOR_PRODUCAO_ID NUMBER(10) NOT NULL,
  COMPONENTE VARCHAR2(200) NOT NULL,
  PERCENTAGEM FLOAT(10) NOT NULL
);

CREATE TABLE TIPO_PLANTA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SEMEADURA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  QUANTIDADE_SEMENTE FLOAT(10) NOT NULL,
  CULTURA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE MONDA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  AREA FLOAT(10) NOT NULL,
  CULTURA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE PLANTACAO (
  OPERACAO_ID NUMBER(10) NOT NULL,
  NUM_PLANTAS NUMBER(10) NOT NULL,
  COMPASSO NUMBER(10),
  DISTANCIA_FILAS NUMBER(10),
  CULTURA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE REGA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  DURACAO NUMBER(10) NOT NULL,
  SETOR_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE COLHEITA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  QUANTIDADE NUMBER(10) NOT NULL,
  PRODUTO_ID NUMBER(10) NOT NULL,
  CULTURA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE MOVIMENTACAO_SOLO (
  OPERACAO_ID NUMBER(10) NOT NULL,
  AREA FLOAT(10) NOT NULL,
  PARCELA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE APLICACAO_FP_SOLO (
  OPERACAO_ID NUMBER(10) NOT NULL,
  PARCELA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE APLICACAO_FP (
  OPERACAO_ID NUMBER(10) NOT NULL,
  AREA FLOAT(10),
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE APLICACAO_FP_CULTURA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  CULTURA_ID NUMBER(10) NOT NULL,
  MODO_AFP_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE MODO_AFP (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(200) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE FP_APLICADOS (
  OPERACAO_ID NUMBER(10) NOT NULL,
  FP_ID NUMBER(10) NOT NULL,
  QUANTIDADE NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID, FP_ID)
);

CREATE TABLE SETOR (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DATA_INICIAL TIMESTAMP(0) NOT NULL,
  DATA_FINAL TIMESTAMP(0),
  CAUDAL_MAXIMO FLOAT(10) NOT NULL,
  NUM_SETOR NUMBER(10) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE FERTIRREGA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  RECEITA NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

CREATE TABLE RECEITA_FERTIRREGA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  NUM_RECEITA NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE FP_RECEITA (
  RECEITA_ID NUMBER(10) NOT NULL,
  FP_ID NUMBER(10) NOT NULL,
  QUANTIDADE NUMBER(10) NOT NULL
);

CREATE TABLE PODA (
  OPERACAO_ID NUMBER(10) NOT NULL,
  QUANTIDADE FLOAT(10),
  CULTURA_ID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAO_ID)
);

ALTER TABLE CULTURA ADD CONSTRAINT FKCULTURA793187 FOREIGN KEY (PARCELA_ID) REFERENCES PARCELA_AGRICOLA (ID);

ALTER TABLE PRODUTO ADD CONSTRAINT FKPRODUTO637620 FOREIGN KEY (PLANTA_ID) REFERENCES PLANTA (ID);

ALTER TABLE COMPONENTE ADD CONSTRAINT FKCOMPONENTE336563 FOREIGN KEY (FATOR_PRODUCAO_ID) REFERENCES FATOR_PRODUCAO (ID);

ALTER TABLE CULTURA ADD CONSTRAINT FKCULTURA385034 FOREIGN KEY (PLANTA_ID) REFERENCES PLANTA (ID);

ALTER TABLE PLANTA ADD CONSTRAINT FKPLANTA586474 FOREIGN KEY (TIPO_PLANTA_ID) REFERENCES TIPO_PLANTA (ID);

ALTER TABLE SEMEADURA ADD CONSTRAINT FKSEMEADURA878528 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE SEMEADURA ADD CONSTRAINT FKSEMEADURA342739 FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA (ID);

ALTER TABLE MONDA ADD CONSTRAINT FKMONDA789751 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE MONDA ADD CONSTRAINT FKMONDA960570 FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA (ID);

ALTER TABLE PLANTACAO ADD CONSTRAINT FKPLANTACAO963769 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE PLANTACAO ADD CONSTRAINT FKPLANTACAO786552 FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA (ID);

ALTER TABLE REGA ADD CONSTRAINT FKREGA773435 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE COLHEITA ADD CONSTRAINT FKCOLHEITA249376 FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID);

ALTER TABLE COLHEITA ADD CONSTRAINT FKCOLHEITA410021 FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA (ID);

ALTER TABLE COLHEITA ADD CONSTRAINT FKCOLHEITA340301 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE MOVIMENTACAO_SOLO ADD CONSTRAINT FKMOVIMENTAC188490 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE MOVIMENTACAO_SOLO ADD CONSTRAINT FKMOVIMENTAC168301 FOREIGN KEY (PARCELA_ID) REFERENCES PARCELA_AGRICOLA (ID);

ALTER TABLE APLICACAO_FP ADD CONSTRAINT FKAPLICACAO_401044 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE APLICACAO_FP_SOLO ADD CONSTRAINT FKAPLICACAO_381515 FOREIGN KEY (OPERACAO_ID) REFERENCES APLICACAO_FP (OPERACAO_ID);

ALTER TABLE APLICACAO_FP_SOLO ADD CONSTRAINT FKAPLICACAO_847241 FOREIGN KEY (PARCELA_ID) REFERENCES PARCELA_AGRICOLA (ID);

ALTER TABLE APLICACAO_FP_CULTURA ADD CONSTRAINT FKAPLICACAO_932937 FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA (ID);

ALTER TABLE APLICACAO_FP_CULTURA ADD CONSTRAINT FKAPLICACAO_599743 FOREIGN KEY (OPERACAO_ID) REFERENCES APLICACAO_FP (OPERACAO_ID);

ALTER TABLE APLICACAO_FP_CULTURA ADD CONSTRAINT FKAPLICACAO_324158 FOREIGN KEY (MODO_AFP_ID) REFERENCES MODO_AFP (ID);

ALTER TABLE FP_APLICADOS ADD CONSTRAINT FKFP_APLICAD286628 FOREIGN KEY (OPERACAO_ID) REFERENCES APLICACAO_FP (OPERACAO_ID);

ALTER TABLE FP_APLICADOS ADD CONSTRAINT FKFP_APLICAD389859 FOREIGN KEY (FP_ID) REFERENCES FATOR_PRODUCAO (ID);

ALTER TABLE REGA ADD CONSTRAINT FKREGA591594 FOREIGN KEY (SETOR_ID) REFERENCES SETOR (ID);

ALTER TABLE FP_RECEITA ADD CONSTRAINT FKFP_RECEITA91311 FOREIGN KEY (RECEITA_ID) REFERENCES RECEITA_FERTIRREGA (ID);

ALTER TABLE FP_RECEITA ADD CONSTRAINT FKFP_RECEITA922460 FOREIGN KEY (FP_ID) REFERENCES FATOR_PRODUCAO (ID);

ALTER TABLE FERTIRREGA ADD CONSTRAINT FKFERTIRREGA159558 FOREIGN KEY (RECEITA) REFERENCES RECEITA_FERTIRREGA (ID);

ALTER TABLE FERTIRREGA ADD CONSTRAINT FKFERTIRREGA373004 FOREIGN KEY (OPERACAO_ID) REFERENCES REGA (OPERACAO_ID);

ALTER TABLE CULTURA ADD CONSTRAINT FKCULTURA206816 FOREIGN KEY (SETOR_ID) REFERENCES SETOR (ID);

ALTER TABLE PODA ADD CONSTRAINT FKPODA823500 FOREIGN KEY (OPERACAO_ID) REFERENCES OPERACAO (ID);

ALTER TABLE PODA ADD CONSTRAINT FKPODA926821 FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA (ID);