CREATE USER bddad IDENTIFIED BY bddad123;
GRANT CREATE SESSION TO bddad;
GRANT CREATE TABLE TO bddad;
GRANT CREATE TRIGGER TO bddad;
GRANT CREATE PROCEDURE TO bddad;
GRANT CREATE FUNCTION TO bddad;
GRANT INSERT, UPDATE, DELETE ON bddad.table_name TO bddad;
GRANT CREATE ANY TABLE TO bddad;
GRANT ALTER ANY TABLE TO bddad;
