/* Inserir plantas */
INSERT INTO planta (especie, nome_comum, variedade, tipo_plantacao) values ('Cucurbita moschata', 'Abobora', 'Manteiga', 'Temporaria');

/* Inserir Parcela */
INSERT INTO PARCELA_AGRICOLA (
    ID,
    DESIGNACAO,
    AREA,
    UNIDADE
) VALUES (
    150,
    'Campo Novo',
    1.1,
    'ha'
);

 /* Inserir Fatores de producao */ 
 
 INSERT INTO FATOR_PRODUCAO (
    DESIGNACAO,
    FABRICANTE,
    FORMATO,
    TIPO,
    APLICACAO
) VALUES (
    'Fertimax Extrume de Cavalo',
    'Nutrofertil',
    'Granulado',
    'Adubo',
    'Adubo Solo'
);

INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Azoto Organico (N)', 3);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Fosforo total (P205)', 0.8);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Potassio total (K2O)', 0.4);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Calcio total (Ca)', 1.6);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Magnesio total (MgO)', 0.3);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Boro total (B)', 0.004);

 INSERT INTO FATOR_PRODUCAO (
    DESIGNACAO,
    FABRICANTE,
    FORMATO,
    TIPO,
    APLICACAO
) VALUES (
    'BIOFERTIL N6',
    'Nutrofertil',
    'Granulado',
    'Adubo',
    'Adubo Solo'
);

INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Azoto Organico (N)', 6.4);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Fosforo total (P205)', 2.5);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Potassio total (K2O)', 2.4);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Calcio total (Ca)', 6);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Magnesio total (MgO)', 0.3);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Boro total (B)', 0.0020);

/* Inserir Culturas */
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 30, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Grande'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Oliveira' AND VARIEDADE = 'Galega'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 20, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Grande'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Oliveira' AND VARIEDADE = 'Picual'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Grande'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Oliveira' AND VARIEDADE = 'Arbequina'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 90, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Jonagored'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 60, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Fuji'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Royal Gala'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 30, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Royal Gala'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Pipo De Basto'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 50, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Porta Da Loja'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 20, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Malapio'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 30, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Canada'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Grand Fay'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 50, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Gronho Doce'));

INSERT INTO CULTURA (data_inicial, data_final, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2023-04-05', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'),100, '%', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Novo'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Cenoura' AND VARIEDADE = 'Sugarsnax Hybrid'));
INSERT INTO CULTURA (data_inicial, data_final, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2023-07-05', 'YYYY-MM-DD'), TO_DATE('2023-10-08', 'YYYY-MM-DD'),100, '%', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Novo'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Cenoura' AND VARIEDADE = 'Danvers Half Long'));

INSERT INTO CULTURA (data_inicial, data_final, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2023-04-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'),100, '%', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Novo'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Abobora' AND VARIEDADE = 'Manteiga'));

/* Inserir Operacoes Rega */
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

/* Inserir Operacoes Colheita Lameiro Da Ponte  */
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-08-18', 'YYYY-MM-DD'), 'Colheita', 700.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Royal Gala' AND PA.DESIGNACAO = 'Lameiro Da Ponte' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-08-30', 'YYYY-MM-DD'), 'Colheita', 900.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Royal Gala' AND PA.DESIGNACAO = 'Lameiro Da Ponte' AND C.DATA_INICIAL = TO_DATE('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-05', 'YYYY-MM-DD'), 'Colheita', 900.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Jonagored' AND PA.DESIGNACAO = 'Lameiro Da Ponte' AND C.DATA_INICIAL = TO_DATE('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-08', 'YYYY-MM-DD'), 'Colheita', 1050.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Jonagored' AND PA.DESIGNACAO = 'Lameiro Da Ponte' AND C.DATA_INICIAL = TO_DATE('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-28', 'YYYY-MM-DD'), 'Colheita', 950.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Fuji' AND PA.DESIGNACAO = 'Lameiro Da Ponte' AND C.DATA_INICIAL = TO_DATE('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-10-03', 'YYYY-MM-DD'), 'Colheita', 800.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Fuji' AND PA.DESIGNACAO = 'Lameiro Da Ponte' AND C.DATA_INICIAL = TO_DATE('01/05/2017', 'DD/MM/YYYY')));

/*test operacoes colheita in lameiro da ponte*/
DECLARE
    LISTA         SYS_REFCURSOR;
    NOME          VARCHAR2(20);
    PLANTA_ID     NUMBER;
    QUANTIDADE_KG FLOAT;
    V_PARCELA     VARCHAR2(20) := 'Lameiro Da Ponte';
    DATA_INICIAL  DATE := TO_DATE('2015-08-01', 'YYYY-MM-DD');
    DATA_FINAL    DATE := TO_DATE('2023-11-30', 'YYYY-MM-DD');
BEGIN
    LISTA := LISTA_PRODUTOS_COLHIDOS (V_PARCELA, DATA_INICIAL, DATA_FINAL);
    dbms_output.put_line ('PLANTA_ID | NOME | QUANTIDADE_KG');
    DBMS_OUTPUT.PUT_LINE ('----------------------------------------------------------------------');
    LOOP
        FETCH LISTA INTO PLANTA_ID, NOME, QUANTIDADE_KG;
        EXIT WHEN LISTA%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE (PLANTA_ID
                              || ' | '
                              || NOME
                              || ' | '
                              || QUANTIDADE_KG || ' kg');
    END LOOP;
    CLOSE LISTA;
END;
/



/*insert operacao 'Aplicacaoo de Fator de Producao' and 'Fator_Producao' */
INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('N6', 'BIOFERTIL', )
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-04', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 3200.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE IS NULL AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
/*insert plantaçoes*/
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-09', 'YYYY-MM-DD'), 'Plantação', 50.0, 'Un', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Porta da Loja' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-09', 'YYYY-MM-DD'), 'Plantação', 20.0, 'Un', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Malápio' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-10', 'YYYY-MM-DD'), 'Plantação', 40.0, 'Un', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Pipo de Basto' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-10', 'YYYY-MM-DD'), 'Plantação', 30.0, 'Un', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Canada' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-11', 'YYYY-MM-DD'), 'Plantação', 40.0, 'Un', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Grand Fay' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2019-01-11', 'YYYY-MM-DD'), 'Plantação', 50.0, 'Un', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Gronho Doce' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2020-01-06', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 100.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Porta da Loja' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2020-01-06', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 40.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Malápio' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2020-01-06', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 80.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Pipo de Basto' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('10/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2020-01-06', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 60.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Canada' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('10/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2020-01-07', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 80.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Grand Fay' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('11/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2020-01-07', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 100.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Gronho Doce' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('11/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2021-01-07', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 150.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Porta da Loja' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2021-01-07', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 60.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Malápio' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2021-01-08', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 120.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Pipo de Basto' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('10/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2021-01-07', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 90.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Canada' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('10/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2021-01-07', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 120.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Grand Fay' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('11/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2021-01-08', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 150.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Gronho Doce' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('11/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 5.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Porta da Loja' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 2.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Malápio' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 4.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Pipo de Basto' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('10/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 3.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Canada' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('10/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 4.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Grand Fay' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('11/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Aplicação de Fator de Produção', 5.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM IS NULL AND P.VARIEDADE = 'Gronho Doce' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('11/01/2019', 'DD/MM/YYYY')));


/* Inserir Operacoes Colheita Lameiro Do Moinho */

INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-15', 'YYYY-MM-DD'), 'Colheita', 700.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Canada' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-16', 'YYYY-MM-DD'), 'Colheita', 600.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Grand Fay' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-20', 'YYYY-MM-DD'), 'Colheita', 700.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON C.PARCELA_ID = PA.ID  WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Grand Fay' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-09-27', 'YYYY-MM-DD'), 'Colheita', 600.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA PA ON  C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Pipo de Basto' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-10-05', 'YYYY-MM-DD'), 'Colheita', 700.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA  PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Pipo de Basto' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-10-15', 'YYYY-MM-DD'), 'Colheita', 1200.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA  PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Gronho Doce' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));   
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-10-15', 'YYYY-MM-DD'), 'Colheita', 700.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA  PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Malápio' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-11-12', 'YYYY-MM-DD'), 'Colheita', 700.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA  PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Porta da Loja' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (DATA, TIPO_OPERACAO, QUANTIDADE, UNIDADES, CULTURA_ID) VALUES (TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'Colheita', 800.0, 'Kg', (SELECT C.ID FROM CULTURA C LEFT JOIN PLANTA P ON C.PLANTA_ID = P.ID LEFT JOIN PARCELA_AGRICOLA  PA ON C.PARCELA_ID = PA.ID WHERE  P.NOME_COMUM = 'Macieira' AND P.VARIEDADE = 'Porta da Loja' AND PA.DESIGNACAO = 'Lameiro Do Moinho' AND C.DATA_INICIAL = TO_DATE('09/01/2019', 'DD/MM/YYYY')));

/*test operacoes colheita in Lameiro Do Moinho */
DECLARE
    LISTA         SYS_REFCURSOR;
    NOME          VARCHAR2(20);
    PLANTA_ID     NUMBER;
    QUANTIDADE_KG FLOAT;
    V_PARCELA     VARCHAR2(20) := 'Lameiro Do Moinho';
    DATA_INICIAL  DATE := TO_DATE('2015-08-01', 'YYYY-MM-DD');
    DATA_FINAL    DATE := TO_DATE('2023-11-30', 'YYYY-MM-DD');
BEGIN
    LISTA := LISTA_PRODUTOS_COLHIDOS (V_PARCELA, DATA_INICIAL, DATA_FINAL);
    dbms_output.put_line ('PLANTA_ID | NOME | QUANTIDADE_KG');
    DBMS_OUTPUT.PUT_LINE ('----------------------------------------------------------------------');
    LOOP
        FETCH LISTA INTO PLANTA_ID, NOME, QUANTIDADE_KG;
        EXIT WHEN LISTA%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE (PLANTA_ID
                              || ' | '
                              || NOME
                              || ' | '
                              || QUANTIDADE_KG || ' kg');
    END LOOP;
    CLOSE LISTA;
END;
/


/* INSERIR OPERAÇOES DE REGA EM LAMEIRO DO MOINHO */

/*ONE INSERT FOR EACH CULTURA IN SETOR 22 (LAMEIRO DO MOINHO)*/

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('13/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('13/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('13/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('13/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('13/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('16/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('16/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('16/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('16/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('16/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id  left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('22/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('22/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('22/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('22/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('22/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('29/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('29/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('29/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('29/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('29/07/2023', 'DD/MM/YYYY'), 'Rega', 180, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa  on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('09/01/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('05/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('05/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('05/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('05/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('05/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('10/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('10/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('10/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('10/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('10/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id   left join PARCELA_AGRICOLA  pa on c.parcela_id = pa.id  where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('17/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('17/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('17/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('17/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('17/08/2023', 'DD/MM/YYYY'), 'Rega', 150, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('24/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('24/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('24/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('24/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('24/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id    left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id   where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')))20

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('02/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')))20

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('09/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('09/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('09/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('09/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('09/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id     left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id    where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id      left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id     where p.nome_comum = 'Macieira' and p.variedade = 'Porta da Loja' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id      left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id     where p.nome_comum = 'Macieira' and p.variedade = 'Malápio' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id      left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id     where p.nome_comum = 'Macieira' and p.variedade = 'Canada' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id      left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id     where p.nome_comum = 'Macieira' and p.variedade = 'Grand Fay' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id      left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id     where p.nome_comum = 'Macieira' and p.variedade = 'Gronho Doce' and pa.designacao = 'Lameiro Do Moinho' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));


/*OPERACOES CAMPO GRANDE*/



/*OPERACOES CAMPO NOVO*/



SELECT * FROM OPERACAO WHERE TIPO_OPERACAO = 'Colheita';


Select * from PARCELA_AGRICOLA WHERE DESIGNACAO LIKE 'Lameiro%';
Select * from Planta WHERE VARIEDADE LIKE 'Grand%'

Delete From Cultura 

Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY');

Select * from operacao where tipo_operacao = 'Rega';