/* Inserir plantas */
INSERT INTO planta (especie, nome_comum, variedade, tipo_plantacao) values ('Cucurbita moschata', 'Abobora', 'Manteiga', 'Temporaria');

/* Inserir Parcela */
INSERT INTO PARCELA_AGRICOLA (
    ID,
    DESIGNACAO,
    AREA,
    UNIDADE
) VALUES (
    150,
    'Campo Novo',
    1.1,
    'ha'
);

 /* Inserir Fatores de producao */ 
 
 INSERT INTO FATOR_PRODUCAO (
    DESIGNACAO,
    FABRICANTE,
    FORMATO,
    TIPO,
    APLICACAO
) VALUES (
    'Fertimax Extrume de Cavalo',
    'Nutrofertil',
    'Granulado',
    'Adubo',
    'Adubo Solo'
);

INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Azoto Organico (N)', 3);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Fosforo total (P205)', 0.8);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Potassio total (K2O)', 0.4);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Calcio total (Ca)', 1.6);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Magnesio total (MgO)', 0.3);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Boro total (B)', 0.004);

 INSERT INTO FATOR_PRODUCAO (
    DESIGNACAO,
    FABRICANTE,
    FORMATO,
    TIPO,
    APLICACAO
) VALUES (
    'BIOFERTIL N6',
    'Nutrofertil',
    'Granulado',
    'Adubo',
    'Adubo Solo'
);

INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Azoto Organico (N)', 6.4);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Fosforo total (P205)', 2.5);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Potassio total (K2O)', 2.4);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Calcio total (Ca)', 6);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Magnesio total (MgO)', 0.3);
INSERT INTO COMPONENTE (fator_producao_id, componente, percentagem) values ((Select id from FATOR_PRODUCAO where designacao = 'Fertimax Extrume de Cavalo'), 'Boro total (B)', 0.0020);

/* Inserir Culturas */
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 30, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Grande'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Oliveira' AND VARIEDADE = 'Galega'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 20, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Grande'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Oliveira' AND VARIEDADE = 'Picual'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Grande'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Oliveira' AND VARIEDADE = 'Arbequina'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 90, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Jonagored'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 60, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Fuji'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Royal Gala'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 30, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Royal Gala'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Da Ponte'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Pipo De Basto'));

INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 50, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Porta Da Loja'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 20, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Malapio'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 30, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Canada'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 40, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Grand Fay'));
INSERT INTO CULTURA (data_inicial, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 50, 'un', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Lameiro Do Moinho'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Macieira' AND VARIEDADE = 'Gronho Doce'));

INSERT INTO CULTURA (data_inicial, data_final, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2023-04-05', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'),100, '%', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Novo'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Cenoura' AND VARIEDADE = 'Sugarsnax Hybrid'));
INSERT INTO CULTURA (data_inicial, data_final, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2023-07-05', 'YYYY-MM-DD'), TO_DATE('2023-10-08', 'YYYY-MM-DD'),100, '%', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Novo'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Cenoura' AND VARIEDADE = 'Danvers Half Long'));

INSERT INTO CULTURA (data_inicial, data_final, quantidade, unidades, parcela_id, planta_id) values (TO_DATE('2023-04-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'),100, '%', (SELECT id FROM PARCELA_AGRICOLA WHERE DESIGNACAO = 'Campo Novo'), (SELECT id FROM PLANTA WHERE NOME_COMUM = 'Abobora' AND VARIEDADE = 'Manteiga'));

/* Inserir Operacoes */
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Fuji' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Royal Gala' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));

INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/05/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('30/06/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('07/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('14/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('21/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('28/07/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('04/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('11/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('18/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('25/08/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('01/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('08/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));
INSERT INTO OPERACAO (data, tipo_operacao, quantidade, unidades, cultura_id) values (to_date('15/09/2023', 'DD/MM/YYYY'), 'Rega', 120, 'min', (Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Pipo De Basto' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2019', 'DD/MM/YYYY')));



Select * from PARCELA_AGRICOLA WHERE DESIGNACAO LIKE 'Lameiro%';
Select * from Planta WHERE VARIEDADE LIKE 'Grand%'

Delete From Cultura 

Select c.id from cultura c left join Planta p on c.planta_id = p.id left join PARCELA_AGRICOLA pa on c.parcela_id = pa.id where p.nome_comum = 'Macieira' and p.variedade = 'Jonagored' and pa.designacao = 'Lameiro Da Ponte' and c.data_inicial = to_date('01/05/2017', 'DD/MM/YYYY');

Select * from operacao where tipo_operacao = 'Rega';