DROP table PLANTAS;
DROP table Fator_Plantacao;
DROP table Explocaracao_Agricula;
DROP table Parcela;
DROP table Culturas;
DROP table Operacoes;

create table Plantas (
    id int GENERATED by default as IDENTITY,
    especie varchar(50) not null,
    nome_comum varchar(50) not null,
    variedade varchar(50) not null,
    tipo_plantacao varchar(50) not null,
    data_plantacao date,
    poda varchar(70),
    floracao varchar(70),
    colheita varchar(70),

    primary key (id)
);

create table Fator_Plantacao (
    id NUMBER GENERATED by default as IDENTITY,
    designacao varchar(50) not null,
    fabricante varchar(50) not null,
    formato varchar(50) not null,
    tipo varchar(50) not null,
    aplicacao varchar(50) not null,
    c1 varchar(50) not null,
    perc_c1 FLOAT not null,
    c2 varchar(50),
    perc_c2 FLOAT,
    c3 varchar(50),
    perc_c3 FLOAT,
    c4 varchar(50),
    perc_c4 FLOAT,

    primary key (id),
    check (perc_c1 > 0 and perc_c1 <= 100),
    check (perc_c2 > 0 and perc_c2 <= 100),
    check (perc_c3 > 0 and perc_c3 <= 100),
    check (perc_c4 > 0 and perc_c4 <= 100)

);

create table Explocaracao_Agricula (
    id NUMBER GENERATED by default as IDENTITY,
    tipo varchar(50) not null,
    designacao varchar(50) not null,
    area FLOAT,
    unidade varchar(50),

    primary key (id)
);

create table Parcela (
    id NUMBER GENERATED by default as IDENTITY,
    designacao varchar(50) not null,

    primary key (id)
);

create table Culturas (
    id NUMBER GENERATED by default as IDENTITY,
    id_parcela int not null,
    id_planta int not null,
    data_inicial date not null,
    data_final date,
    quantidade FLOAT not null,
    unidade varchar(50) not null,

    primary key (id),

    foreign key (id_parcela) references Parcela(id),
    foreign key (id_planta) references Plantas(id),

    check (quantidade > 0)
);

create table Operacoes (
    id NUMBER GENERATED by default as IDENTITY,
    id_cultura int not null,
    id_fator_producao int,
    operacao varchar(50) not null,
    modo varchar(50),
    data date not null,
    quantidade FLOAT,
    unidade varchar(50),

    primary key (id),

    foreign key (id_cultura) references Culturas(id),
    foreign key (id_fator_producao) references Fator_Plantacao(id)
);

