CREATE TABLE OPERATIONS_LOG (
    LOG_ID NUMBER(10) GENERATED AS IDENTITY,
    LOG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OPERATION_ID NUMBER(10) NOT NULL,
    OPERATION_TYPE VARCHAR2(200) NOT NULL,
    OPERATION_DATE DATE NOT NULL,
    OPERATION_STATE VARCHAR2(200) DEFAULT 'sucedida',
    ADDITIONAL_INFO CLOB,
    PRIMARY KEY (LOG_ID)
);

CREATE OR REPLACE TRIGGER LOG_SEMEADURA_OPERATION
AFTER INSERT OR UPDATE ON SEMEADURA
FOR EACH ROW
DECLARE
    v_operation_date TIMESTAMP;
    v_operation_state VARCHAR2(200);
    v_additional_info CLOB;
BEGIN
    SELECT DATA, ESTADO INTO v_operation_date, v_operation_state FROM OPERACAO WHERE ID=:NEW.OPERACAO_ID;

    v_additional_info := {
        "quantidade_de_semente": :NEW.QUANTIDADE_SEMENTE,
        "cultura_id": :NEW.CULTURA_ID,
    };

    INSERT INTO OPERATIONS_LOG (OPERATION_ID, OPERATION_TYPE, OPERATION_DATE, OPERATION_STATE, ADDITIONAL_INFO) VALUES (:NEW.OPERACAO_ID, 'Semeadura', v_operation_date, v_operation_state, v_additional_info);
END;
/

CREATE OR REPLACE TRIGGER LOG_COLHEITA_OPERATION
AFTER INSERT OR UPDATE ON COLHEITA
FOR EACH ROW
DECLARE
    v_operation_date TIMESTAMP;
    v_operation_state VARCHAR2(200);
    v_additional_info CLOB;
BEGIN
    SELECT DATA, ESTADO INTO v_operation_date, v_operation_state FROM OPERACAO WHERE ID=:NEW.OPERACAO_ID;

    v_additional_info := {
        "quantidade_colhida": :NEW.QUANTIDADE,
        "cultura_id": :NEW.CULTURA_ID,
        "product_id:": :NEW.PRODUTO_ID,
    };

    INSERT INTO OPERATIONS_LOG (OPERATION_ID, OPERATION_TYPE, OPERATION_DATE, OPERATION_STATE, ADDITIONAL_INFO) VALUES (:NEW.OPERACAO_ID, 'Colheita', v_operation_date, v_operation_state, v_additional_info);
END;
/