DECLARE
    V_ID_TIPO_PLANTA INTEGER;
    V_ID_PLANTA INTEGER;
    V_ID_FATOR_PRODUCAO INTEGER;
    V_ID_COMPONENTE INTEGER;
    V_ID_PARCELA INTEGER;
    V_ID_CULTURA INTEGER;
    V_ID_OPERACAO INTEGER;
    V_ID_PRODUTO INTEGER;
BEGIN


INSERT INTO TIPO_PLANTA (DESIGNACAO) VALUES ('Cucurbita Moschata')
RETURNING ID INTO V_ID_TIPO_PLANTA;

INSERT INTO PLANTA (NOME, TIPO_PLANTA_ID) VALUES ('Abobora Manteiga', V_ID_TIPO_PLANTA)
RETURNING ID INTO V_ID_PLANTA;

INSERT INTO PARCELA_AGRICOLA (DESIGNACAO, AREA) VALUES ('Campo Novo', 1.1)
RETURNING ID INTO V_ID_PARCELA;

INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('Fertimax Extrume De Cavalo', 'Nutrofertil', 'Granulado', 'Adubo', 'Solo')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Materia Organica', 50)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Azoto Organico', 3)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Fosforo Total', 0.8)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Potassio Total', 0.4)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Calcio Total', 1.6)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Magnesio Total', 0.3)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Boro Total', 0.004)
RETURNING ID INTO V_ID_COMPONENTE;


INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('BIOFERTIL N6', 'Nutrofertil', 'Granulado', 'Adubo', 'Solo')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Materia Organica', 53)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Azoto Organico', 6.4)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Fosforo Total', 2.5)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Potassio Total', 2.4)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Calcio Total', 6)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Magnesio Total', 0.3)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Boro Total', 0.002)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('Tecniferti MOL', 'Tecniferti', 'Liquido', 'Materia Organica', 'Liquida')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;

INSERT INTO COMPONENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Materia Organica', 27)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Azoto', 3.6)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Azoto Organico', 2)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Fosforo Total', 1)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Potassio Total', 3)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Carbono Organico Total', 15)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Acidos Fulvicos', 10)
RETURNING ID INTO V_ID_COMPONENTE;


INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('SoluSOP 52', 'K+S', 'Po Molhavel', 'Adubo', 'Organico')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Enxofre', 45)
RETURNING ID INTO V_ID_COMPONENTE;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Potassio Total', 52.5)
RETURNING ID INTO V_ID_COMPONENTE;


INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('Floracal Flow SL', 'Plymag', 'Liquido', 'Adubo', 'Liquido')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Oxido De Calcio', 35)
RETURNING ID INTO V_ID_COMPONENTE;


INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('Kiplant AllGrip', 'Asfertglobal', 'Liquido', 'Adubo', 'Liquido')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;


INSERT INTO FATOR_PRODUCAO (DESIGNACAO, FABRICANTE, FORMATO, TIPO, APLICACAO) VALUES ('Cuperdem', 'Asfertglobal', 'Liquido', 'Adubo', 'Liquido')
RETURNING ID INTO V_ID_FATOR_PRODUCAO;

INSERT INTO COMPOENTE (FATOR_PRODUCAO_ID, COMPONENTE, PERCENTAGEM) VALUES (V_ID_FATOR_PRODUCAO, 'Cobre', 6)






INSERT INTO SETOR (DATA_INICIAL, CAUDAL_MAXIMO, NUM_SETOR) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 2500, 10)
RETURNING ID INTO V_ID_SETOR;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Campo Grande', Select ID From PLANTA Where NOME = 'Galega', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Campo Grande', Select ID From PLANTA Where NOME = 'Picual', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;


INSERT INTO SETOR (DATA_INICIAL, CAUDAL_MAXIMO, NUM_SETOR) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 1500, 11)
RETURNING ID INTO V_ID_SETOR;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Campo Grande', Select ID From PLANTA Where NOME = 'Arbequina', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;


INSERT INTO SETOR (DATA_INICIAL, CAUDAL_MAXIMO, NUM_SETOR) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), 3500, 21)
RETURNING ID INTO V_ID_SETOR;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Jonagored', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Fuji', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2017-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Royal Gala', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Royal Gala', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Pipo de Basto', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;


INSERT INTO SETOR (DATA_INICIAL, CAUDAL_MAXIMO, NUM_SETOR) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), 3500, 22)
RETURNING ID INTO V_ID_SETOR;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Porta Da Loja', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Malapio', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Canada', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Grand Fay', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2019-05-01', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Do Moinho', Select ID From PLANTA Where NOME = 'Gronho Doce', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;


INSERT INTO SETOR (DATA_INICIAL, CAUDAL_MAXIMO, NUM_SETOR) VALUES (TO_DATE('2023-04-01', 'YYYY-MM-DD'), 2500, 41)
RETURNING ID INTO V_ID_SETOR;

INSERT INTO CULTURA (DATA_INICIAL, DATA_FINAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2023-04-05', 'YYYY-MM-DD'), TO_DATE('2023-05-31', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Campo Novo', Select ID From PLANTA Where NOME = 'Sugarsnax Hybrid', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;

INSERT INTO CULTURA (DATA_INICIAL, DATA_FINAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2023-04-05', 'YYYY-MM-DD'), TO_DATE('2023-10-08', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Campo Novo', Select ID From PLANTA Where NOME = 'Danvers Half Long', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;


INSERT INTO SETOR (DATA_INICIAL, CAUDAL_MAXIMO, NUM_SETOR) VALUES (TO_DATE('2023-04-01', 'YYYY-MM-DD'), 3500, 42)
RETURNING ID INTO V_ID_SETOR;

INSERT INTO CULTURA (DATA_INICIAL, DATA_FINAL, PARCELA_ID, PLANTA_ID, SETOR_ID) VALUES (TO_DATE('2023-04-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Campo Novo', Select ID From PLANTA Where NOME = 'Manteiga', V_ID_SETOR)
RETURNING ID INTO V_ID_CULTURA;


INSERT INTO RECEITA_FERTIRREGA (NUM_RECEITA) VALUES (10)
RETURNING ID INTO V_ID_RECEITA_FERTIRREGA;

INSERT INTO FP_RECEITA (RECEITA_ID, FP_ID, QUANTIDADE) VALUES (V_ID_RECEITA_FERTIRREGA, Select ID From FATOR_PRODUCAO Where DESIGNACAO = 'EPSO TOP' AND FABRICANTE = 'K+S', 1.5)
RETURNING ID INTO V_ID_FP_RECEITA;

INSERT INTO FP_RECEITA (RECEITA_ID, FP_ID, QUANTIDADE) VALUES (V_ID_RECEITA_FERTIRREGA, Select ID From FATOR_PRODUCAO Where DESIGNACAO = 'soluSOP 52' AND FABRICANTE = 'K+S', 2.5)
RETURNING ID INTO V_ID_FP_RECEITA;

INSERT INTO FP_RECEITA (RECEITA_ID, FP_ID, QUANTIDADE) VALUES (V_ID_RECEITA_FERTIRREGA, Select ID From FATOR_PRODUCAO Where DESIGNACAO = 'Floracal Flow SL' AND FABRICANTE = 'Plymag', 1.7)
RETURNING ID INTO V_ID_FP_RECEITA;


INSERT INTO RECEITA_FERTIRREGA (NUM_RECEITA) VALUES (11)
RETURNING ID INTO V_ID_RECEITA_FERTIRREGA;

INSERT INTO FP_RECEITA (RECEITA_ID, FP_ID, QUANTIDADE) VALUES (V_ID_RECEITA_FERTIRREGA, Select ID From FATOR_PRODUCAO Where DESIGNACAO = 'Tecniferti MOL' AND FABRICANTE = 'Tecniferti', 60)
RETURNING ID INTO V_ID_FP_RECEITA;

INSERT INTO FP_RECEITA (RECEITA_ID, FP_ID, QUANTIDADE) VALUES (V_ID_RECEITA_FERTIRREGA, Select ID From FATOR_PRODUCAO Where DESIGNACAO = 'Kiplant AllGrip' AND FABRICANTE = 'Asfertglobal', 2)
RETURNING ID INTO V_ID_FP_RECEITA;



-- LAMEIRO DA PONTE 

-- Operaçoes de Rega:
INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-05-14 07:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-06-01 07:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-06-15 07:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-06-30 07:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-07-07 07:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 180, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-07-14 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 180, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-07-21 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 180, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-07-28 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 180, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-08-04 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 150, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-08-11 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 150, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-08-18 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 150, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-08-25 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-09-01 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-09-08 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-09-15 22:00', 'YYYY-MM-DD HH24:MI'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO REGA (OPERACAO_ID, DURACAO, SETOR_ID) VALUES (V_ID_OPERACAO, 120, Select ID From SETOR Where NUM_SETOR = 21)
RETURNING ID INTO V_ID_REGA;

--Operaçoes de Colheita 
--- FIX ME (insert nos produtos? ou ja existem?)
INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-08-18', 'YYYY-MM-DD'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO COLHEITA (OPERACAO_ID, QUANTIDADE, PRODUTO_ID, CULTURA_ID) VALUES (V_ID_OPERACAO, 700, Select ID From PRODUTO Where NOME = 'Maça', Select ID From CULTURA Where PLANTA_ID = (Select ID From PLANTA Where NOME = 'Royal Gala') AND PARCELA_ID = (Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho'))
RETURNING ID INTO V_ID_COLHEITA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-08-30', 'YYYY-MM-DD'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO COLHEITA (OPERACAO_ID, QUANTIDADE, PRODUTO_ID, CULTURA_ID) VALUES (V_ID_OPERACAO, 900, Select ID From PRODUTO Where NOME = 'Maça', Select ID From CULTURA Where PLANTA_ID = (Select ID From PLANTA Where NOME = 'Royal Gala') AND PARCELA_ID = (Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho'))
RETURNING ID INTO V_ID_COLHEITA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-09-05', 'YYYY-MM-DD'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO COLHEITA (OPERACAO_ID, QUANTIDADE, PRODUTO_ID, CULTURA_ID) VALUES (V_ID_OPERACAO, 900, Select ID From PRODUTO Where NOME = 'Maça', Select ID From CULTURA Where PLANTA_ID = (Select ID From PLANTA Where NOME = 'Jonagored') AND PARCELA_ID = (Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho'))
RETURNING ID INTO V_ID_COLHEITA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-09-08', 'YYYY-MM-DD'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO COLHEITA (OPERACAO_ID, QUANTIDADE, PRODUTO_ID, CULTURA_ID) VALUES (V_ID_OPERACAO, 1050, Select ID From PRODUTO Where NOME = 'Maça', Select ID From CULTURA Where PLANTA_ID = (Select ID From PLANTA Where NOME = 'Jonagored') AND PARCELA_ID = (Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho'))
RETURNING ID INTO V_ID_COLHEITA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-09-28', 'YYYY-MM-DD'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO COLHEITA (OPERACAO_ID, QUANTIDADE, PRODUTO_ID, CULTURA_ID) VALUES (V_ID_OPERACAO, 950, Select ID From PRODUTO Where NOME = 'Maça', Select ID From CULTURA Where PLANTA_ID = (Select ID From PLANTA Where NOME = 'Fuji') AND PARCELA_ID = (Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho'))
RETURNING ID INTO V_ID_COLHEITA;


INSERT INTO OPERACAO (DATA) VALUES (TO_DATE('2023-10-03', 'YYYY-MM-DD'))
RETURNING ID INTO V_ID_OPERACAO;

INSERT INTO COLHEITA (OPERACAO_ID, QUANTIDADE, PRODUTO_ID, CULTURA_ID) VALUES (V_ID_OPERACAO, 800, Select ID From PRODUTO Where NOME = 'Maça', Select ID From CULTURA Where PLANTA_ID = (Select ID From PLANTA Where NOME = 'Fuji') AND PARCELA_ID = (Select ID From PARCELA_AGRICOLA Where DESIGNACAO = 'Lameiro Da Ponte' OR DESIGNACAO = 'Lameiro Do Moinho'))
RETURNING ID INTO V_ID_COLHEITA;



-- LAMEIRO DO MOINHO 












END;
