CREATE OR REPLACE TRIGGER prevent_delete
BEFORE DELETE ON OPERATIONS_LOG
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'You are not allowed to delete from this table!');
END;
/

CREATE OR REPLACE TRIGGER prevent_update
BEFORE UPDATE ON OPERATIONS_LOG
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'You are not allowed to update this table!');
    ROLLBACK
END;
/

--TEST TRIGGER DELETE

DELETE FROM OPERATIONS_LOG WHERE LOG_ID = 1;


--TEST TRIGGER UPDATE

UPDATE OPERATIONS_LOG SET OPERATION_STATE = 'deve dar erro' WHERE LOG_ID = 1;


