/*
USBD27 Como Gestor Agrícola, pretendo que não seja possível alterar ou apagar os logs.
*/

CREATE OR REPLACE TRIGGER PREVENT_DELETE BEFORE
  DELETE ON OPERATIONS_LOG FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'You are not allowed to delete from this table!');
END;
/

CREATE OR REPLACE TRIGGER PREVENT_UPDATE BEFORE
  UPDATE ON OPERATIONS_LOG FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'You are not allowed to update this table!');
END;
/

SELECT
  *
FROM
  OPERATIONS_LOG
WHERE
  LOG_ID = 1;

--TEST TRIGGER DELETE
DELETE FROM OPERATIONS_LOG
WHERE
  LOG_ID = 1;

SELECT
  *
FROM
  OPERATIONS_LOG
WHERE
  LOG_ID = 1;

--TEST TRIGGER UPDATE
UPDATE OPERATIONS_LOG
SET
  OPERATION_STATE = 'deve dar erro'
WHERE
  LOG_ID = 1;

SELECT
  *
FROM
  OPERATIONS_LOG
WHERE
  LOG_ID = 1;